
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label3;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry pantalla;
	private global::Gtk.Button Ok;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label2;
	private global::Gtk.Entry pantalla2;
	private global::Gtk.Button Okk;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Ypad = 18;
		this.label3.Xalign = 0.97F;
		this.label3.Yalign = 0.99F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("¡BIENVENIDO!\n\nEste programa le servirá para convertir números Decimales a Romanos. Por favor, tenga en cuenta que los números romanos básicos se encuentran en el rango de 0 a 3999.");
		this.label3.Wrap = true;
		this.label3.Justify = ((global::Gtk.Justification)(2));
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Padding = ((uint)(20));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Número Decimal:");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.pantalla = new global::Gtk.Entry ();
		this.pantalla.CanFocus = true;
		this.pantalla.Name = "pantalla";
		this.pantalla.IsEditable = true;
		this.pantalla.InvisibleChar = '•';
		this.hbox1.Add (this.pantalla);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.pantalla]));
		w3.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Ok = new global::Gtk.Button ();
		this.Ok.CanFocus = true;
		this.Ok.Name = "Ok";
		this.Ok.UseUnderline = true;
		this.Ok.Label = global::Mono.Unix.Catalog.GetString ("Convertir");
		this.hbox1.Add (this.Ok);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Ok]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Número Romano:");
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.pantalla2 = new global::Gtk.Entry ();
		this.pantalla2.CanFocus = true;
		this.pantalla2.Name = "pantalla2";
		this.pantalla2.IsEditable = true;
		this.pantalla2.InvisibleChar = '•';
		this.hbox2.Add (this.pantalla2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.pantalla2]));
		w7.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Okk = new global::Gtk.Button ();
		this.Okk.CanFocus = true;
		this.Okk.Name = "Okk";
		this.Okk.UseUnderline = true;
		this.Okk.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.hbox2.Add (this.Okk);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Okk]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 330;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Ok.Clicked += new global::System.EventHandler (this.OnOkClicked);
		this.Okk.Clicked += new global::System.EventHandler (this.OnOkkClicked);
	}
}
